In [1]:
# Import workalendar library from https://github.com/peopledoc/workalendar
import datetime as dt
from workalendar.europe import France

In [2]:
# Getting a list of holidays for a year with Workalendar
cal = France()
cal.holidays(2012)

[(datetime.date(2012, 1, 1), 'New year'),
 (datetime.date(2012, 4, 9), 'Easter Monday'),
 (datetime.date(2012, 5, 1), 'Labour Day'),
 (datetime.date(2012, 5, 8), 'Victory in Europe Day'),
 (datetime.date(2012, 5, 17), 'Ascension Thursday'),
 (datetime.date(2012, 5, 28), 'Whit Monday'),
 (datetime.date(2012, 7, 14), 'Bastille Day'),
 (datetime.date(2012, 8, 15), 'Assumption of Mary to Heaven'),
 (datetime.date(2012, 11, 1), 'All Saints Day'),
 (datetime.date(2012, 11, 11), 'Armistice Day'),
 (datetime.date(2012, 12, 25), 'Christmas Day')]

In [3]:
# Getting the number of days off in a month in a specific year, in this example June 2016

cal.get_working_days_delta(dt.date(2016, 6, 1), dt.date(2016, 6, 30))
from calendar import monthrange

holidays_6_2016 = monthrange(2016, 6)[1] - cal.get_working_days_delta(dt.date(2016, 6, 1), 
                                                                      dt.date(2016, 6, 30))
print(holidays_6_2016)

9

In [4]:
# Getting number of days off in France per month for specific year(s)

def daysoff(y,m):
    nbdays = monthrange(y, m)[1]
    return(nbdays - cal.get_working_days_delta(dt.date(y, m, 1), dt.date(y, m, nbdays)))

# daysoff(2018,5)

# for y in range(2016,2019):
#     for m in range(1,13):
#         print(daysoff(y,m))
    
# list_daysoff = [daysoff(y,m) for y in range(2016,2019) for m in range(1,13)]
# list_daysoff


# Manually change range of years you want to calculate for on the following line:
dict_daysoff = {dt.date(y, m, 1): daysoff(y,m) for y in range(2016,2019) for m in range(1,13)}
dict_daysoff

import pandas as pd

daysoff_series = pd.Series(dict_daysoff)
daysoff_series

2016-01-01    11
2016-02-01     9
2016-03-01    10
2016-04-01    10
2016-05-01    11
2016-06-01     9
2016-07-01    12
2016-08-01    10
2016-09-01     9
2016-10-01    10
2016-11-01    10
2016-12-01    10
2017-01-01     9
2017-02-01     9
2017-03-01     9
2017-04-01    11
2017-05-01    11
2017-06-01    10
2017-07-01    11
2017-08-01    10
2017-09-01    10
2017-10-01     9
2017-11-01     9
2017-12-01    12
2018-01-01     9
2018-02-01     9
2018-03-01    10
2018-04-01    10
2018-05-01    12
2018-06-01    10
2018-07-01     9
2018-08-01    10
2018-09-01    10
2018-10-01     9
2018-11-01     9
2018-12-01    11
dtype: int64

In [5]:
daysoff_df = daysoff_series.to_frame()
daysoff_df.columns = ['NbDaysOff']
daysoff_df

            NbDaysOff
2016-01-01         11
2016-02-01          9
2016-03-01         10
2016-04-01         10
2016-05-01         11
2016-06-01          9
2016-07-01         12
2016-08-01         10
2016-09-01          9
2016-10-01         10
2016-11-01         10
2016-12-01         10
2017-01-01          9
2017-02-01          9
2017-03-01          9
2017-04-01         11
2017-05-01         11
2017-06-01         10
2017-07-01         11
2017-08-01         10
2017-09-01         10
2017-10-01          9
2017-11-01          9
2017-12-01         12
2018-01-01          9
2018-02-01          9
2018-03-01         10
2018-04-01         10
2018-05-01         12
2018-06-01         10
2018-07-01          9
2018-08-01         10
2018-09-01         10
2018-10-01          9
2018-11-01          9
2018-12-01         11

In [13]:
daysoff_df.to_csv('daysoff1.csv')