## A) Importing libraries

In [1]:
import pandas as pd
import numpy as np
import datetime 
import matplotlib.pyplot as plt
%matplotlib inline

## B) Datasets (2010-2017)
1. Hotel nights for regions bordering Pays de la loire
2. Weather for regions bordering Pays de la loire
3. Gross regional product
4. Airports in the region
5. Days off

### 1. Hotel nights dataset - Already have a clean CSV

In [2]:
data_nights = pd.read_csv('/Users/jinny/Documents/touristcast/exercises/datasets/hotel_nights_FR_by-region.csv')
data_nights.head()

,Date,NbNights_Île-de-France,NbNights_Centre-Val de Loire,NbNights_Bourgogne-Franche-Comté,NbNights_Normandie,NbNights_Hauts-de-France,NbNights_Grand Est,NbNights_Pays de la Loire,NbNights_Bretagne,NbNights_Nouvelle-Aquitaine,NbNights_Occitanie,NbNights_Auvergne-Rhône-Alpes,NbNights_Provence-Alpes-Côte d'Azur,NbNights_Corse
0,2017-12-01,5636.91,340.56,432.92,424.48,652.83,1305.32,426.76,415.64,839.74,836.23,1725.25,1038.43,35.13
1,2017-11-01,5344.01,377.57,471.98,505.72,702.61,1036.71,485.82,488.47,949.19,847.34,1326.84,1120.95,46.21
2,2017-10-01,6199.86,500.96,609.30,658.58,800.96,1266.90,576.17,637.19,1383.63,1389.69,1616.60,1828.70,227.34
3,2017-09-01,6040.26,594.91,725.11,772.73,850.44,1371.82,700.65,815.28,1638.24,1776.25,1931.24,2367.31,551.19
4,2017-08-01,5694.74,738.31,834.17,979.76,856.48,1529.35,870.02,1131.36,2387.15,2426.26,2592.87,3365.52,681.86

### 2a) Weather dataset - Importing and removing useless columns

In [4]:
weather_2010_2015 = pd.read_csv('/Users/jinny/Documents/touristcast/exercises/datasets/meteo_2010_2015.csv')
weather_2016_2017 = pd.read_csv('/Users/jinny/Documents/touristcast/exercises/datasets/meteo_2016_2017.csv')
weather = weather_2010_2015.append(weather_2016_2017)
weather = weather[['year', 'month', 'region', 'Température moyenne']]

# Renaming AvgTemp column and removing celsius symbol
weather = weather.rename(columns={'Température moyenne': 'AvgTemp'})
weather['AvgTemp'] = weather['AvgTemp'].map(lambda x: x.rstrip('°'))

# ****Make sure to convert AvgTemp into integer float format after importing CSV****
weather.AvgTemp = weather.AvgTemp.astype('float')
weather.head()

   year    month  region  AvgTemp
0  2010  janvier  alsace     -1.0
1  2010  février  alsace      1.0
2  2010     mars  alsace      5.0
3  2010    avril  alsace     11.0
4  2010      mai  alsace     12.0

### 2b) Weather dataset - Converting dates to the correct format and setting dates as index

In [5]:
# Dict to map FR month names to month number and convert month name to number
month_format = dict(zip(weather.month, range(1,13)))
month_format

weather['month'] = weather['month'].apply(lambda x: month_format[x])

# Adding day column for the first of each month so we can convert YYYY/MM/DD with pd.to_datetime below
weather['day'] = 1
weather = weather[['year', 'month', 'day', 'region', 'AvgTemp']]

# Combining and converting dates to single column in format datetime
weather = weather.assign(date=pd.to_datetime(weather[['year', 'month', 'day']]))

weather = weather[['date', 'region', 'AvgTemp']]

# Setting Date column as index and reordering dates in ascending order
weather = weather.set_index('date')

In [6]:
weather.tail()

                 region  AvgTemp
date
2017-08-01  rh-ne-alpes     25.0
2017-09-01  rh-ne-alpes     16.0
2017-10-01  rh-ne-alpes     15.0
2017-11-01  rh-ne-alpes      6.0
2017-12-01  rh-ne-alpes      2.0

### 2c) Weather dataset - Combining old regions into 6 new regions, weighted by regional surface area

In [17]:
# Pivot dataframe so that each region is a separate column 
weather = weather.pivot(columns='region', values='AvgTemp')

# Rename dataframe as all values are avgtemp now 
avg_temp = weather

# Dictionary that maps regions which need to be combined
region_fusion = {'GrandEst': ['alsace','champagne-ardenne','lorraine'], 
               'Nouvelle-Aquitaine': ['aquitaine','limousin','poitou-charentes'],
               'Auvergne-Rhone-Alpes': ['auvergne','rh-ne-alpes'],
               'Bourgogne-Franche-Comte': ['bourgogne','franche-comte'],
               'Occitanie': ['languedoc-roussillon', 'midi-pyrenees'],
               'Hauts-de-France': ['nord-pas-de-calais','picardie']}

# Dictionary that shows surface areas for each old region, to be used as weights in average
surface_area = {'alsace': 8280, 'champagne-ardenne': 25606, 'lorraine': 23547, 
                'aquitaine': 41308, 'limousin': 16942, 'poitou-charentes': 25809,
                'auvergne': 15582, 'rh-ne-alpes': 43698, 
                'bourgogne': 31582, 'franche-comte': 16202,
                'languedoc-roussillon': 27376, 'midi-pyrenees': 45348,
                'nord-pas-de-calais': 12414, 'picardie': 19399}

# Convert surface area dictionary to series so that np.average can call it
surface = pd.Series(surface_area)

# Create new row with new region name that contains weighted average of old regions
for new_region, old_regions in region_fusion.items():
    avg_temp[new_region] = avg_temp[old_regions].apply(
        lambda temperatures: np.average(temperatures, weights=surface[old_regions]), axis=1)

# List of regions that haven't been fusioned/changed
unchanged_regions = ['bretagne', 'corse', 'centre', 'ile-de-france', 
                     'pays-de-la-loire', 'provence-alpes-c-te-d-azur', 'normandie']

# Dataframe with average temperatures per month for the 13 regions
avg_temp = avg_temp[unchanged_regions + list(region_fusion)]
avg_temp.tail()

KeyError: 'region'

In [18]:
avg_temp = avg_temp.add_prefix('AvgTemp_')
avg_temp.head()

region,AvgTemp_bretagne,AvgTemp_corse,AvgTemp_centre,AvgTemp_ile-de-france,AvgTemp_pays-de-la-loire,AvgTemp_provence-alpes-c-te-d-azur,AvgTemp_normandie,AvgTemp_GrandEst,AvgTemp_Nouvelle-Aquitaine,AvgTemp_Auvergne-Rhone-Alpes,AvgTemp_Bourgogne-Franche-Comte,AvgTemp_Occitanie,AvgTemp_Hauts-de-France
date,,,,,,,,,,,,,
2010-01-01,6.0,10.0,2.0,2.0,4.0,5.0,4.0,-0.554159,4.886770,-0.474291,0.321865,4.129311,2.000000
2010-02-01,7.0,11.0,4.0,4.0,7.0,7.0,6.0,2.301673,6.088319,1.525709,2.321865,5.129311,4.000000
2010-03-01,8.0,12.0,7.0,8.0,8.0,9.0,8.0,6.301673,9.088319,4.525709,6.321865,7.752874,7.390218
2010-04-01,12.0,15.0,12.0,12.0,13.0,14.0,11.0,11.000000,13.781285,10.262854,11.660933,13.752874,11.000000
2010-05-01,13.0,18.0,14.0,14.0,14.0,17.0,13.0,12.445841,14.596902,12.000000,12.660933,15.129311,13.000000

### 3) Days off dataset - Already has a clean CSV

In [8]:
# Import and set date as index
daysoff = pd.read_csv('/Users/jinny/Documents/touristcast/exercises/datasets/daysoff_2010-2017.csv', index_col=0)

# Convert index to datetime format
daysoff.index = pd.to_datetime(daysoff.index)

daysoff.tail()

            NbDaysOff
2017-08-01         10
2017-09-01         10
2017-10-01          9
2017-11-01          9
2017-12-01         12

### 4a) Airports dataset - Importing and formatting

In [9]:
airports = pd.read_csv('/Users/jinny/Documents/touristcast/Other_DS/Airports_FR_2018_clean_by_regions.csv', sep=';')
airports = airports.dropna()
airports = airports.drop('Code', axis=1)
airports = airports.set_index('Nom')

### 4b) Airports dataset - Fill in dates from 2010 to 2017 with number of airports
* This dataset won't be used in the final version as models do not accept constant values as inputs

In [10]:
# Generate a list of dates (first day per month) from 2010 to 2017
startyear = 2010
startmonth = 1
endyear = 2017
endmonth = 12
month_list = list([datetime.date(m//12, m%12+1, 1) for m in range(startyear*12+startmonth-1, 
                                                endyear*12+endmonth)])
month_list = np.asarray(month_list)

# Add list of months and columns and fill columns with number of airports per region
for month in month_list:
    airports[month] = np.nan
    airports[month] = airports[month].fillna(airports.Airports_nb, axis=0)

# Dataframe with dates as index instead of columns and regions as columns
airports = airports.drop('Airports_nb', axis=1)
airports = airports.transpose()
airports = airports.add_prefix('NbAirports_')

In [11]:
print(airports.columns)
airports.tail()

Index(['NbAirports_Auvergne-Rhône-Alpes', 'NbAirports_Bourgogne-Franche-Comté',
       'NbAirports_Bretagne', 'NbAirports_Centre-Val de Loire',
       'NbAirports_Corse', 'NbAirports_Grand Est',
       'NbAirports_Hauts-de-France', 'NbAirports_Île-de-France',
       'NbAirports_Normandie', 'NbAirports_Nouvelle-Aquitaine',
       'NbAirports_Occitanie', 'NbAirports_Pays de la Loire',
       'NbAirports_Provence-Alpes-Côte d'Azur'],
      dtype='object', name='Nom')

Nom,NbAirports_Auvergne-Rhône-Alpes,NbAirports_Bourgogne-Franche-Comté,NbAirports_Bretagne,NbAirports_Centre-Val de Loire,NbAirports_Corse,NbAirports_Grand Est,NbAirports_Hauts-de-France,NbAirports_Île-de-France,NbAirports_Normandie,NbAirports_Nouvelle-Aquitaine,NbAirports_Occitanie,NbAirports_Pays de la Loire,NbAirports_Provence-Alpes-Côte d'Azur
2017-08-01,14.0,3.0,8.0,3.0,5.0,7.0,5.0,4.0,5.0,13.0,11.0,7.0,5.0
2017-09-01,14.0,3.0,8.0,3.0,5.0,7.0,5.0,4.0,5.0,13.0,11.0,7.0,5.0
2017-10-01,14.0,3.0,8.0,3.0,5.0,7.0,5.0,4.0,5.0,13.0,11.0,7.0,5.0
2017-11-01,14.0,3.0,8.0,3.0,5.0,7.0,5.0,4.0,5.0,13.0,11.0,7.0,5.0
2017-12-01,14.0,3.0,8.0,3.0,5.0,7.0,5.0,4.0,5.0,13.0,11.0,7.0,5.0

### 5) Regional Gross Domestic Product (FR: Produits intérieurs bruts régionaux) per region Dataset
- Produits Intérieurs Bruts Régionaux (PIBR) en valeur en millions d'euros

In [12]:
regional_GDP = pd.read_excel('/Users/jinny/Documents/touristcast/exercises/datasets/PIB_1990_2015_regions_diffusion.xls', 
                             sheet_name='PIB en valeur 1990-2015',
                            header=3)
regional_GDP = regional_GDP[['Année', 2010,2011,2012,2013,2014,2015]]
regional_GDP = regional_GDP.rename(columns={'Année': 'Region'})
regional_GDP = regional_GDP.set_index('Region')
regional_GDP = regional_GDP.drop(['Région', 'Province', 'Métropole', 
                                 'Guadeloupe', 'Martinique', 'Guyane',
                                 'Mayotte', 'DOM', 'Réunion', 'Source Insee , Comptes régionaux base 2010', "en millions d'euros"])
regional_GDP = regional_GDP[:-2]
regional_GDP

,2010,2011,2012,2013,2014,2015
Region,,,,,,
Auvergne-Rhône-Alpes,225165.722898,235357.207896,237266.294057,240201.169190,244275.0,250120.0
Bourgogne-Franche-Comté,70109.284504,72588.290718,71496.346881,71834.915911,73119.0,73942.0
Bretagne,81299.450684,85011.055111,86154.197563,87600.593103,89654.0,91910.0
Centre-Val de Loire,65690.501206,67831.191046,68243.749827,68750.758224,69131.0,70355.0
Corse,7923.515907,8250.710059,8341.352943,8470.375152,8592.0,8868.0
Grand Est,142866.822031,148739.087423,147276.098091,149011.229417,150621.0,152170.0
Hauts-de-France,144983.739632,150222.933177,150400.287532,152133.184334,153494.0,156922.0
Île-de-France,609979.484932,615750.076702,629506.942141,643624.203923,652859.0,668823.0
Normandie,85549.671843,88601.974141,88929.911653,89839.720706,90075.0,91740.0
Nouvelle-Aquitaine,148172.239621,154505.326716,156646.620149,157717.594237,160880.0,163898.0
Occitanie,140183.733846,146556.847176,149653.163099,151741.816950,155320.0,159115.0
Pays de la Loire,96709.073745,101976.384463,103234.648490,104948.398040,106990.0,109767.0
Provence-Alpes-Côte d'Azur,143112.575866,146235.111809,150297.768142,149988.491724,152061.0,154879.0

In [15]:
# Add list of months and columns and fill columns with GDP per region
for year in range(2010, 2016):
    for month in range(1,13):
        date = datetime.datetime.strptime(f'{year}-{month}-01', '%Y-%m-%d')
        regional_GDP[date] = regional_GDP[year]

regional_GDP = regional_GDP.drop(list(range(2010, 2016)), axis=1)
regional_GDP.columns = pd.to_datetime(regional_GDP.columns)
regional_GDP = regional_GDP.transpose()
regional_GDP.head()

Region,Auvergne-Rhône-Alpes,Bourgogne-Franche-Comté,Bretagne,Centre-Val de Loire,Corse,Grand Est,Hauts-de-France,Île-de-France,Normandie,Nouvelle-Aquitaine,Occitanie,Pays de la Loire,Provence-Alpes-Côte d'Azur
2010-01-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-02-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-03-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-04-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-05-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-06-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-07-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-08-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-09-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-10-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-11-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2010-12-01,225165.722898,70109.284504,81299.450684,65690.501206,7923.515907,142866.822031,144983.739632,609979.484932,85549.671843,148172.239621,140183.733846,96709.073745,143112.575866
2011-01-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-02-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-03-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-04-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-05-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-06-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-07-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-08-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-09-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-10-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-11-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2011-12-01,235357.207896,72588.290718,85011.055111,67831.191046,8250.710059,148739.087423,150222.933177,615750.076702,88601.974141,154505.326716,146556.847176,101976.384463,146235.111809
2012-01-01,237266.294057,71496.346881,86154.197563,68243.749827,8341.352943,147276.098091,150400.287532,629506.942141,88929.911653,156646.620149,149653.163099,103234.648490,150297.768142
2012-02-01,237266.294057,71496.346881,86154.197563,68243.749827,8341.352943,147276.098091,150400.287532,629506.942141,88929.911653,156646.620149,149653.163099,103234.648490,150297.768142
2012-03-01,237266.294057,71496.346881,86154.197563,68243.749827,8341.352943,147276.098091,150400.287532,629506.942141,88929.911653,156646.620149,149653.163099,103234.648490,150297.768142
2012-04-01,237266.294057,71496.346881,86154.197563,68243.749827,8341.352943,147276.098091,150400.287532,629506.942141,88929.911653,156646.620149,149653.163099,103234.648490,150297.768142
2012-05-01,237266.294057,71496.346881,86154.197563,68243.749827,8341.352943,147276.098091,150400.287532,629506.942141,88929.911653,156646.620149,149653.163099,103234.648490,150297.768142
2012-06-01,237266.294057,71496.346881,86154.197563,68243.749827,8341.352943,147276.098091,150400.287532,629506.942141,88929.911653,156646.620149,149653.163099,103234.648490,150297.768142
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-07-01,240201.169190,71834.915911,87600.593103,68750.758224,8470.375152,149011.229417,152133.184334,643624.203923,89839.720706,157717.594237,151741.816950,104948.398040,149988.491724
2013-08-01,240201.169190,71834.915911,87600.593103,68750.758224,8470.375152,149011.229417,152133.184334,643624.203923,89839.720706,157717.594237,151741.816950,104948.398040,149988.491724
2013-09-01,240201.169190,71834.915911,87600.593103,68750.758224,8470.375152,149011.229417,152133.184334,643624.203923,89839.720706,157717.594237,151741.816950,104948.398040,149988.491724
2013-10-01,240201.169190,71834.915911,87600.593103,68750.758224,8470.375152,149011.229417,152133.184334,643624.203923,89839.720706,157717.594237,151741.816950,104948.398040,149988.491724
2013-11-01,240201.169190,71834.915911,87600.593103,68750.758224,8470.375152,149011.229417,152133.184334,643624.203923,89839.720706,157717.594237,151741.816950,104948.398040,149988.491724
2013-12-01,240201.169190,71834.915911,87600.593103,68750.758224,8470.375152,149011.229417,152133.184334,643624.203923,89839.720706,157717.594237,151741.816950,104948.398040,149988.491724
2014-01-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-02-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-03-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-04-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-05-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-06-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-07-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-08-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-09-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-10-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-11-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2014-12-01,244275.000000,73119.000000,89654.000000,69131.000000,8592.000000,150621.000000,153494.000000,652859.000000,90075.000000,160880.000000,155320.000000,106990.000000,152061.000000
2015-01-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-02-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-03-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-04-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-05-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-06-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-07-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-08-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-09-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-10-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-11-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000
2015-12-01,250120.000000,73942.000000,91910.000000,70355.000000,8868.000000,152170.000000,156922.000000,668823.000000,91740.000000,163898.000000,159115.000000,109767.000000,154879.000000

In [21]:
regional_GDP = regional_GDP.add_prefix('GDP_')

### Export datasets as CSV

In [19]:
# Dataset for monthly weather by region from 2010-2017
avg_temp.to_csv('avgtemp_2010-2017.csv')

In [22]:
# Dataset for yearly regional GDP from 2010-2015
regional_GDP.to_csv('regionalGDP_2010-2015.csv')